---

services:
  backend1:
    image: catchbook-backend:last
    container_name: catchbook-backend-1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ps

  backend2:
    image: catchbook-backend:last
    container_name: catchbook-backend-2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ps

  nginx:
    build: services/server
    ports:
      - "10000:80"
    networks:
      - ps
    depends_on:
      - backend1
      - backend2

  frontend:
    image: catchbook-frontend:last
    container_name: catchbook-frontned
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ps
    ports:
      - "10001:80"
    environment:
      - NGINX_HOST=catchbook.develop
      - NGINX_PORT=80

  db:
    image: mysql:8
    container_name: catchbook-db
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "13306:3306"
    networks:
      - ps
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

networks:
  ps: