---

services:
  app:
    image: catchbook:local
    container_name: catchbook
    ports:
      - "10000:10000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ps

  db:
    image: mysql:8
    container_name: catchbook-db
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "13306:3306"
    networks:
      - ps
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10


networks:
  ps: